#Nhan Le
#Sep 5, 2022
#Lab3
#Purpose of makefile: compiling and execute lab3

all: lab3 #create excecute variable

lab3:	symtable.c symtable.h
	gcc symtable.c -o lab3	#compile target

run:	lab3
	./lab3

clean: 
	rm -f lab3
